image: alpine/edge
packages:
  - gcc
  - clang
  - meson
sources:
  - https://github.com/emersion/mrsh
tasks:
  - setup: |
      cd mrsh
      mkdir build-{gcc,clang}
      CC=gcc meson build-gcc
      CC=clang meson build-clang
  - gcc: |
      cd mrsh
      ninja -C build-gcc
  - clang: |
      cd mrsh
      ninja -C build-clang
