image: alpine/latest
packages:
  - rsync
secrets:
  - 77c7956b-003e-44f7-bb5c-2944b2047654 # SSH deploy key
sources:
  - https://git.sr.ht/~emersion/mrsh#website
tasks:
  - upload: |
      cd mrsh
      sshopts="-o StrictHostKeyChecking=no"
      rsync --rsh="ssh $sshopts" -rP \
          --exclude .git \
          --delete \
          --delete-excluded \
          . deploy@sheeta.emersion.fr:/srv/http/mrsh
