image: archlinux
packages:
  - gcc
  - meson
  - readline
sources:
  - https://git.sr.ht/~emersion/mrsh
tasks:
  - setup: |
      cd mrsh
      meson build -Db_sanitize=address,undefined -Dreadline=enabled
  - build: |
      cd mrsh
      ninja -C build
  - test: |
      cd mrsh
      ninja -C build test
  - build-release: |
      cd mrsh
      meson configure build --buildtype release
      ninja -C build
  - build-no-readline: |
      cd mrsh
      meson configure build -Dreadline=disabled
      ninja -C build
triggers:
  - action: email
    condition: failure
    to: "<contact@emersion.fr>"
