image: freebsd
packages:
  - meson
sources:
  - https://github.com/emersion/mrsh
tasks:
  - setup: |
      cd mrsh
      meson build
  - build: |
      cd mrsh
      ninja -C build
  - test: |
      cd mrsh
      ninja -C build test
triggers:
  - action: email
    condition: failure
    to: "<contact@emersion.fr>"
